// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn5iYE-tFiXkSmYNB2lSxbX9UBzlC_Dvo',
    appId: '1:1093304427329:web:930a95953e13e5f216f7c0',
    messagingSenderId: '1093304427329',
    projectId: 'fiutte-firestore',
    authDomain: 'fiutte-firestore.firebaseapp.com',
    storageBucket: 'fiutte-firestore.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSCVpOW3O-LV6gjlhniup6U2a6cG0cIR0',
    appId: '1:1093304427329:android:df31996b284f5fc116f7c0',
    messagingSenderId: '1093304427329',
    projectId: 'fiutte-firestore',
    storageBucket: 'fiutte-firestore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXIp8rGdBK5LcSLvyrhHu8D99kb4cYcxU',
    appId: '1:1093304427329:ios:65da9f5b02850b3516f7c0',
    messagingSenderId: '1093304427329',
    projectId: 'fiutte-firestore',
    storageBucket: 'fiutte-firestore.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXIp8rGdBK5LcSLvyrhHu8D99kb4cYcxU',
    appId: '1:1093304427329:ios:65da9f5b02850b3516f7c0',
    messagingSenderId: '1093304427329',
    projectId: 'fiutte-firestore',
    storageBucket: 'fiutte-firestore.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn5iYE-tFiXkSmYNB2lSxbX9UBzlC_Dvo',
    appId: '1:1093304427329:web:747df864aa1c197d16f7c0',
    messagingSenderId: '1093304427329',
    projectId: 'fiutte-firestore',
    authDomain: 'fiutte-firestore.firebaseapp.com',
    storageBucket: 'fiutte-firestore.firebasestorage.app',
  );
}
